# -*- coding: utf-8 -*-
"""imagetotext

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXKfj3bgRFhFXePQrCOcZkWM4gJlQq6c
"""



!pip install pytesseract
!sudo apt-get install tesseract-ocr

!apt-get install tesseract-ocr-script-hang tesseract-ocr-script-hang-vert tesseract-ocr-script-hani tesseract-ocr-script-hani-vert

!apt-get install tesseract-ocr-script-hangul tesseract-ocr-script-hangul-vert

!apt-get install tesseract-ocr-script-hangul
!apt-get install tesseract-ocr-script-hangul-vert

!wget https://github.com/tesseract-ocr/tessdata/raw/master/script/Hangul.traineddata -P /usr/share/tesseract-ocr/4.00/tessdata/
!wget https://github.com/tesseract-ocr/tessdata/raw/master/script/Hangul_vert.traineddata -P /usr/share/tesseract-ocr/4.00/tessdata/

!sudo apt install tesseract-ocr
!sudo apt install tesseract-ocr-script-hang tesseract-ocr-script-hang-vert

!sudo apt install tesseract-ocr-script-hang

import pytesseract

# Tesseract-OCR의 한국어 언어 데이터 경로 설정
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

from google.colab import drive
import os
import re
from PIL import Image
import pytesseract

# Google Drive 마운트
drive.mount('/content/drive')

# 이미지가 있는 로컬 디렉토리 경로
local_image_directory = '/content/drive/My Drive/네이버 티켓 판매'

# 텍스트 파일 경로 (결과를 저장할 파일)
output_file_path = '/content/drive/My Drive/네이버 티켓 판매/output.txt'

# 텍스트 파일 초기화
with open(output_file_path, "w") as f:
    f.write("")

# 로컬 디렉토리 내의 모든 이미지 파일을 처리
for filename in os.listdir(local_image_directory):
    if filename.endswith(".jpeg") or filename.endswith(".png"):
        image_path = os.path.join(local_image_directory, filename)

        # 이미지 열기
        image = Image.open(image_path)

        # OCR을 사용하여 텍스트 추출
        text = pytesseract.image_to_string(image)

        # 추출된 휴대폰 번호 찾기
        phone_numbers = re.findall(r'\d{3}-\d{4}-\d{4}', text)

        if phone_numbers:
            # 텍스트 파일에 추출된 번호 추가
            with open(output_file_path, "a") as f:
                f.write("\n".join(phone_numbers) + "\n")

# 작업 완료 메시지 출력
print("휴대폰 번호 추출 및 저장이 완료되었습니다.")

!pip install pytesseract pillow







from google.colab import drive
import os
import re
from PIL import Image
import pytesseract
import cv2
import numpy as np

# Google Drive 마운트
drive.mount('/content/drive')

# 이미지가 있는 로컬 디렉토리 경로
local_image_directory = '/content/drive/My Drive/이은서'

# 텍스트 파일 경로 (결과를 저장할 파일)
output_file_path = '/content/drive/My Drive/이은서/output.txt'

# 텍스트 파일 초기화
with open(output_file_path, "w") as f:
    f.write("")

# 로컬 디렉토리 내의 모든 이미지 파일을 처리
for filename in os.listdir(local_image_directory):
    if filename.endswith(".jpeg") or filename.endswith(".png"):
        image_path = os.path.join(local_image_directory, filename)

        # 이미지 열기
        image = Image.open(image_path)

        # OCR을 사용하여 텍스트 추출
        text = pytesseract.image_to_string(image)

        # 추출된 휴대폰 번호 찾기
        phone_numbers = re.findall(r'\d{3}-\d{4}-\d{4}', text)

        if phone_numbers:
            # 텍스트 파일에 추출된 번호 추가
            with open(output_file_path, "a") as f:
                f.write("\n".join(phone_numbers) + "\n")

            # 이미지와 추출된 텍스트 비교
            text_image = Image.new('RGB', (image.width, image.height))
            text_image.paste((255, 255, 255), (0, 0, image.width, image.height))
            text_image = Image.fromarray(np.uint8(text_image))

            # 이미지에 추출된 텍스트 추가
            text_draw = ImageDraw.Draw(text_image)
            text_draw.text((10, 10), text, fill=(0, 0, 0))

            # 이미지와 텍스트 비교
            original_image = cv2.imread(image_path)
            text_image = cv2.cvtColor(np.array(text_image), cv2.COLOR_RGB2BGR)
            difference = cv2.subtract(original_image, text_image)

            if not np.any(difference):
                print(f"이미지와 추출된 텍스트가 일치합니다: {image_path}")
            else:
                print(f"이미지와 추출된 텍스트가 일치하지 않습니다: {image_path}")

# 작업 완료 메시지 출력
print("휴대폰 번호 추출 및 검토가 완료되었습니다.")

